version: 2.1
jobs:
  build:
    docker:
      - image: centos:7
        environment:
          - TZ: "Asia/Tokyo"
          - LANG: "ja_JP.UTF-8"
    working_directory: /circleci
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.09.3"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Check Docker
          command: docker -v
      - run:
          name: Build Docker
          command: |
            docker build -t circleci-workshop:test --target test -f infra/docker/app/Dockerfile .
      - run:
          name: Execute Code Check
          command: |
            docker run \
              -e TZ="Asia/Tokyo" \
              -e LANG="ja_JP.UTF-8" \
              -e APP_ENV="test" \
              circleci-workshop:test composer validate-fmt
      - run:
          name: Static Analysis
          command: |
            docker run \
              -e TZ="Asia/Tokyo" \
              -e LANG="ja_JP.UTF-8" \
              -e APP_ENV="test" \
              circleci-workshop:test composer validate-static
      - run:
          name: Execute Tests
          command: |
            docker run \
              -e TZ="Asia/Tokyo" \
              -e LANG="ja_JP.UTF-8" \
              -e APP_ENV="test" \
              circleci-workshop:test composer test-all

  deploy:
    docker:
      - image: php:7.4-cli
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            echo deploy Finished!!

workflows:
  version: 2
  cicleci_workshop:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
